# Generated by Django 3.2.7 on 2022-06-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
