# Generated by Django 5.0 on 2023-12-15 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_rename_create_at_profile_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_agent",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_buyer",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_seller",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="license",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="num_reviews",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="rationg",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="top_agent",
        ),
    ]
