# Generated by Django 5.0 on 2024-03-07 22:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_remove_profile_is_agent_remove_profile_is_buyer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Full Name"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Address")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("role", models.CharField(max_length=50, verbose_name="Role")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
