# Generated by Django 5.0 on 2024-03-10 13:27

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_parentprofile_delete_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parentprofile",
            old_name="full_name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Occupation"
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="+237680672888",
                max_length=30,
                null=True,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
