# Generated by Django 5.0 on 2024-03-10 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_rename_full_name_parentprofile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parentprofile",
            name="last_name",
        ),
    ]
