#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

cd /app/src


python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
uvicorn Rentals.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload