# Generated by Django 5.0 on 2024-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="is_admin",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="matricule",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
