# Generated by Django 5.0 on 2024-06-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0003_adminprofile_generate_reports_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="is_teacher",
            field=models.BooleanField(default=False, verbose_name="Is Teacher"),
        ),
    ]
