# Generated by Django 5.0 on 2024-06-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_adminprofile_is_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Principal", "Principal"),
                    ("Vice Principal", "Vice Principal"),
                    ("Burser", "Burser"),
                    ("IT", "IT"),
                    ("DM", "DM"),
                    ("Secretary", "Secretary"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
