# Generated by Django 5.0 on 2024-07-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0005_adminprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=200,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="adminprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Principal", "Principal"),
                    ("Vice Principal", "Vice Principal"),
                    ("Burser", "Burser"),
                    ("IT", "IT"),
                    ("DM", "DM"),
                    ("Secretary", "Secretary"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=200,
                verbose_name="Role",
            ),
        ),
    ]
