# Generated by Django 5.0 on 2024-07-05 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0006_alter_adminprofile_gender_alter_adminprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminprofile",
            name="number_of_absences",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
