# Generated by Django 5.0 on 2024-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="endtime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="starttime",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
