# Generated by Django 5.0 on 2024-05-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0002_event_endtime_event_starttime"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Event Location"
            ),
        ),
    ]
