# Generated by Django 5.0 on 2024-06-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0002_adminleave_delete_staffleave"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminleave",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentleave",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacherleave",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
