#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="postgres",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}"
    ) 
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
    >&2 echo "Waiting for PostgreSQL to become available.... "
    >&2 echo ${POSTGRES_DB}
    >&2 echo ${POSTGRES_PASSWORD}
    >&2 echo ${POSTGRES_USER}
    >&2 echo ${POSTGRES_HOST}
    >&2 echo ${POSTGRES_PORT}

    sleep 1
done

>&2 echo "PostgreSQL is ready!!!!..."
>&2 echo ${POSTGRES_DB}
>&2 echo ${POSTGRES_PASSWORD}
>&2 echo ${POSTGRES_USER}
>&2 echo ${POSTGRES_HOST}

exec "$@"