# Generated by Django 5.0 on 2024-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_dailyattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyattendance",
            name="is_present",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dailyattendance",
            name="day",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
