# Generated by Django 5.0 on 2024-07-24 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_dailyattendance_is_present_alter_dailyattendance_day"),
        ("staff", "0008_alter_adminprofile_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyattendance",
            name="taken_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_attendance",
                to="staff.adminprofile",
            ),
        ),
        migrations.AlterField(
            model_name="dailyattendance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
