# Generated by Django 5.0 on 2024-03-07 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("first_term", "First Term"),
                            ("second_term", "Second Term"),
                            ("third_term", "Third Term"),
                        ],
                        default="first_term",
                        max_length=20,
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExaminationSession",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_session",
                    models.CharField(
                        choices=[
                            ("first_sequence", "First Sequence"),
                            ("second_sequence", "Second Sequence"),
                            ("third_sequence", "Third Sequence"),
                            ("fourth_sequence", "Fourth Sequence"),
                            ("fifth_sequence", "Fifth Sequence"),
                            ("sixth_sequence", "Sixth Sequence"),
                            ("seventh_sequence", "Seventh Sequence"),
                        ],
                        default="first_sequence",
                        max_length=20,
                        verbose_name="Exam Sequence",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examination_sessions",
                        to="terms.term",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
