# Generated by Django 5.0 on 2024-03-08 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0002_academicyear_term_academic_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="terms.academicyear"
            ),
        ),
    ]
