# Generated by Django 5.0 on 2024-03-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0004_academicyear_is_current"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
    ]
