# Generated by Django 5.0 on 2024-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0005_alter_academicyear_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
