# Generated by Django 5.0 on 2024-03-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0006_term_is_current"),
    ]

    operations = [
        migrations.AlterField(
            model_name="term",
            name="term",
            field=models.CharField(
                choices=[
                    ("First Term", "First Term"),
                    ("Second Term", "Second Term"),
                    ("Third Term", "Third Term"),
                ],
                default="First Term",
                max_length=20,
                verbose_name="Session",
            ),
        ),
    ]
