# Generated by Django 5.0 on 2024-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0005_reportgenerationstatus_klass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportgenerationstatus",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reportgenerationstatus",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
