# Generated by Django 5.0 on 2024-03-15 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="date_of_payment",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
