# Generated by Django 5.0 on 2024-03-16 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0006_feepaymenthistory_fee_type_alter_fee_fee_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="feepaymenthistory",
            name="fee",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_history",
                to="fees.fee",
            ),
            preserve_default=False,
        ),
    ]
