# Generated by Django 5.0 on 2024-03-25 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0007_feepaymenthistory_fee"),
        ("terms", "0010_alter_examinationsession_exam_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fees_paid",
                to="terms.academicyear",
            ),
        ),
    ]
