# Generated by Django 5.0 on 2024-07-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0008_fee_academic_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="feepaymenthistory",
            name="has_paid_first_installment",
            field=models.BooleanField(default=False),
        ),
    ]
