# Generated by Django 5.0 on 2024-07-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0009_feepaymenthistory_has_paid_first_installment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feepaymenthistory",
            name="has_paid_first_installment",
        ),
        migrations.AlterField(
            model_name="fee",
            name="target",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
