# Generated by Django 5.0 on 2024-07-05 13:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0010_remove_feepaymenthistory_has_paid_first_installment_and_more"),
        ("staff", "0005_adminprofile_role"),
        ("students", "0044_studentprofile_has_paid_pta"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraPayment",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("remark", models.TextField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pay_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.adminprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_payments",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
