# Generated by Django 5.0 on 2024-03-08 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_subject_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attendance",
                to="students.teacherprofile",
            ),
        ),
    ]
