# Generated by Django 5.0 on 2024-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_attendance_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_student",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="matricule",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="matricule",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
