# Generated by Django 5.0 on 2024-03-10 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_studentprofile_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="number_of_absences",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
