# Generated by Django 5.0 on 2024-03-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_remove_subject_teachers"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="main_subject",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Main Subject",
            ),
        ),
    ]
