# Generated by Django 5.0 on 2024-03-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0009_teacherprofile_main_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="main_subject",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Main Subject"
            ),
        ),
    ]
