# Generated by Django 5.0 on 2024-03-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0010_alter_teacherprofile_main_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="calss_prefect",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Class Prefect"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_master",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Class Master"
            ),
        ),
    ]
