# Generated by Django 5.0 on 2024-03-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0012_rename_calss_prefect_class_class_prefect"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="subjects_taught", to="students.teacherprofile"
            ),
        ),
    ]
