# Generated by Django 5.0 on 2024-03-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0013_subject_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="current_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.class",
            ),
        ),
    ]
