# Generated by Django 5.0 on 2024-03-12 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0014_alter_studentprofile_current_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="teachers",
        ),
    ]
