# Generated by Django 5.0 on 2024-03-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0015_remove_subject_teachers"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Subject Code"
            ),
        ),
    ]
