# Generated by Django 5.0 on 2024-03-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0017_remove_subject_klass_class_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="coef",
            field=models.PositiveIntegerField(default=1, verbose_name="Subject Code"),
        ),
    ]
