# Generated by Django 5.0 on 2024-03-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0018_subject_coef"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Subject Name"),
        ),
    ]
