# Generated by Django 5.0 on 2024-03-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0019_alter_subject_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="optional_subjects",
            field=models.ManyToManyField(
                related_name="students_taking", to="students.subject"
            ),
        ),
    ]
