# Generated by Django 5.0 on 2024-03-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0020_studentprofile_optional_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="mark",
            name="remark",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Remark"
            ),
        ),
    ]
