# Generated by Django 5.0 on 2024-03-23 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0021_mark_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mark",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_marks",
                to="students.studentprofile",
            ),
        ),
    ]
