# Generated by Django 5.0 on 2024-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0023_alter_studentprofile_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="Remark"),
        ),
    ]
