# Generated by Django 5.0 on 2024-05-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0025_alter_mark_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="coef",
            field=models.PositiveIntegerField(default=1, verbose_name="Subject Coef"),
        ),
    ]
