# Generated by Django 5.0 on 2024-05-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0026_alter_subject_coef"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="pass_avg",
            field=models.IntegerField(default=10),
        ),
    ]
