# Generated by Django 5.0 on 2024-05-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0027_class_pass_avg"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="best_subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="worst_subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
