# Generated by Django 5.0 on 2024-05-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0029_studentprofile_is_activated"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTempCreateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin", models.CharField(max_length=10, verbose_name="PIN")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.studentprofile",
                        verbose_name="Student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherTempCreateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin", models.CharField(max_length=10, verbose_name="PIN")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "teacher",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.teacherprofile",
                        verbose_name="Student",
                    ),
                ),
            ],
        ),
    ]
