# Generated by Django 5.0 on 2024-06-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0031_teacherprofile_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="classes",
            field=models.ManyToManyField(related_name="teachers", to="students.class"),
        ),
    ]
