# Generated by Django 5.0 on 2024-06-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0033_alter_teacherprofile_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="classes", to="students.subject"
            ),
        ),
    ]
