# Generated by Django 5.0 on 2024-06-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0034_alter_class_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="class",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_subjects",
                to="students.teacherprofile",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="subjects", to="students.subject"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="classes",
            field=models.ManyToManyField(related_name="teachers", to="students.class"),
        ),
    ]
