# Generated by Django 5.0 on 2024-06-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0035_class_assigned_class_assigned_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="assigned",
        ),
        migrations.RemoveField(
            model_name="class",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="subject",
            name="assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subject",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_subjects",
                to="students.teacherprofile",
            ),
        ),
    ]
