# Generated by Django 5.0 on 2024-06-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0036_remove_class_assigned_remove_class_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="classes", to="students.subject"
            ),
        ),
    ]
