# Generated by Django 5.0 on 2024-06-26 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0038_remove_teacherprofile_classes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
