# Generated by Django 5.0 on 2024-06-28 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0039_delete_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="subjects",
        ),
        migrations.AddField(
            model_name="subject",
            name="klass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="students.class",
            ),
        ),
    ]
