# Generated by Django 5.0 on 2024-06-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0040_remove_class_subjects_subject_klass"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="has_class",
            field=models.BooleanField(default=False),
        ),
    ]
