# Generated by Django 5.0 on 2024-07-04 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0042_teacherprofile_appointed_structure_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacherprofile",
            old_name="serivice",
            new_name="service",
        ),
    ]
