# Generated by Django 5.0 on 2024-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0044_studentprofile_has_paid_pta"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="specialty",
            field=models.CharField(default="Civil Engineering", max_length=200),
        ),
    ]
