# Generated by Django 5.0 on 2024-07-16 22:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0045_studentprofile_specialty"),
        ("terms", "0010_alter_examinationsession_exam_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassAcademicRecord",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("class_avg", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "klass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="students.class",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes_academic_records",
                        to="terms.term",
                    ),
                ),
            ],
            options={
                "unique_together": {("klass", "term")},
            },
        ),
    ]
