# Generated by Django 5.0 on 2024-07-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0046_classacademicrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classacademicrecord",
            name="class_avg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
