# Generated by Django 5.0 on 2024-08-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0047_alter_classacademicrecord_class_avg"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="pob",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Place of birth"
            ),
        ),
    ]
