# Generated by Django 5.0 on 2024-08-11 23:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0049_class_class_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Department")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="class",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.department",
            ),
        ),
    ]
