# Generated by Django 5.0 on 2024-08-12 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0050_department_class_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="students.department",
            ),
        ),
    ]
