# Generated by Django 5.0 on 2024-03-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="currency",
            field=models.CharField(
                blank=True,
                help_text="Enter the currency you wish to appear on reciepts (CFA, XAF)",
                max_length=255,
                null=True,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="school_favicon",
            field=models.FileField(
                blank=True, null=True, upload_to="settings", verbose_name="Favicon"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="school_logo",
            field=models.FileField(
                blank=True, null=True, upload_to="settings", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="school_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="School Name"
            ),
        ),
    ]
