# Generated by Django 5.0 on 2024-03-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "settings",
            "0002_alter_setting_currency_alter_setting_school_favicon_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="motto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Motto"
            ),
        ),
    ]
