# Generated by Django 5.0 on 2024-03-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_setting_motto"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="address1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 1"
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="address2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 2"
            ),
        ),
    ]
