# Generated by Django 5.0 on 2024-03-24 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_setting_address1_setting_address2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="address_line1",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="address_line2",
        ),
    ]
