# Generated by Django 5.0 on 2024-03-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0005_remove_setting_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="school_favicon",
            field=models.FileField(
                blank=True, null=True, upload_to="settings/", verbose_name="Favicon"
            ),
        ),
    ]
