# Generated by Django 5.0 on 2024-07-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0008_alter_setting_first_installment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="first_installment",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AlterField(
            model_name="setting",
            name="second_installment",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
