# Generated by Django 5.0 on 2024-07-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0010_alter_setting_first_installment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="pta",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=10000, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="school_uniform",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=10000, max_digits=10, null=True
            ),
        ),
    ]
