# Generated by Django 5.0 on 2024-07-13 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0011_setting_pta_setting_school_uniform"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="next_opening_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
