# Generated by Django 5.0 on 2024-08-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0014_setting_highest_upload_mark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="highest_upload_mark",
            field=models.IntegerField(
                blank=True,
                default=20,
                null=True,
                verbose_name="Highest Marks Allowed for upload",
            ),
        ),
    ]
