from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import StudentProfile, Class
from django.contrib.auth import get_user_model
from apps.profiles.models import ParentProfile
from datetime import datetime, timezone, time
import random


User = get_user_model()

from faker import Faker
faker = Faker()

def list_student_view(request):

    queryset = StudentProfile.objects.all()
    template_name = "students/list.html"
    context = {
        "students": queryset,
    }

    return render(request, template_name, context)


def student_detail_view(request, matricule, pkid):
    student = get_object_or_404(StudentProfile, matricule=matricule, pkid=pkid)

    template_name = "students/details.html"
    context = {
        "student": student
    }

    return render(request, template_name, context)


def add_student_view(request):
    classes = Class.objects.all()
    if request.method == "POST":
        print(request.POST)
        
        parent_fname = request.POST.get("first_name")
        parent_occupation = request.POST.get("parent-occupation")
        parent_phone = request.POST.get("parent-phone")
        parent_email = request.POST.get("parent-email")
        parent_address = request.POST.get("parent-address")
        parent_role = request.POST.get("parent-role")

        st_class = request.POST.get("student_class")
        # Get class in which student is part of
        student_class = get_object_or_404(Class, pkid=int(st_class))

        # Create parent for student
        student_parent = ParentProfile.objects.create(
            first_name=parent_fname,
            phone=parent_phone,
            occupation=parent_occupation,
            address=parent_address,
            email=parent_email,
            role=parent_role
        )

        student_parent.save()

        st_fname = request.POST.get("first_name")
        st_lname = request.POST.get("last_name")
        st_gender = request.POST.get("selected_gender")
        st_email = request.POST.get("email")
        st_dob = request.POST.get("dob")
        st_address = request.POST.get("address")
        st_phone = request.POST.get("phone")
        st_domain = request.POST.get("domain")
        st_image = request.POST.get("image")

        # Create the user instance
        # construct a valid date out of the html date
        date_string_from_form = st_dob

        dob = datetime.strptime(date_string_from_form, '%Y-%m-%d').date()
        # Create a specific time
        specific_time = time(8, 51, 2)

        dob_with_time = datetime.combine(dob, specific_time, tzinfo=timezone.utc)

        # Construct faker usernames, this is done assuming that the usernames are not important to the students
        # we avoid using direct fake usernames, so as to avoid unique constrainst failure in the database
        # This is why the random digit is added to the end of every fake username generated by faker
        faker_username = faker.user_name()
        # attache random digit to the end
        faker_username + str(random.randint(0,9))

 
        user = User.objects.create(
            username=faker_username,
            first_name=st_fname,
            last_name=st_lname,
            email=st_email,
            is_student=True,
            dob=dob_with_time
        )

        user.save()

        if not st_email:
            st_email = faker.email()

        # Create student instance

        student = StudentProfile.objects.create(
            user = user,
            parent = student_parent,
            current_class=student_class,
            gender = st_gender,
            phone_number=st_phone,
            # profile_photo=st_photo,
            address = st_address,
            domain = st_domain,
        )

        student.save()

        return redirect(reverse("students:student-add"))
    else:
        pass
    template_name = "students/add.html"

    context = {
        "classes": classes
    }

    return render(request, template_name, context)


def edit_student_profile(request, pkid, matricule):
    student = get_object_or_404(StudentProfile, pkid=pkid, matricule=matricule)

    if request.method == "POST":
        pass
    
    template_name = "students/edit.html"
    context = {
        'student_profile': student
    }

    return render(request, template_name, context)